spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratelimiter
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true
    open-in-view: false

rate-limit:
  capacity: 5
  refill-tokens: 5
  refill-period-seconds: 1